src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue'
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;
    private $confirm_password;

    /**
     * @ORM\Column(type="string", length=255,unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fullName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $job;

    /**
     * @ORM\OneToMany(targetEntity=UserPhoto::class, mappedBy="user")
     */
    private $userPhotos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adress;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="myFrinds")
     */
    private $Frinds;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="Frinds")
     */
    private $myFrinds;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="userSend")
     */
    private $messagesSend;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="userReceved")
     */
    private $messagesReceved;

    /**
     * @ORM\OneToMany(targetEntity=MessageVu::class, mappedBy="user")
     */
    private $messageVus;

    /**
     * @ORM\OneToOne(targetEntity=Style::class, mappedBy="userStyle", cascade={"persist", "remove"})
     */
    private $style;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="userCreated")
     */
    private $articles;

    /**
     * @ORM\ManyToMany(targetEntity=ArticleVu::class, mappedBy="userVu")
     */
    private $articleVus;

    /**
     * @ORM\ManyToMany(targetEntity=LikeArticle::class, mappedBy="userLike")
     */
    private $likeArticles;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="userComment")
     */
    private $commentaires;

    public function __construct()
    {
        $this->userPhotos = new ArrayCollection();
        $this->Frinds = new ArrayCollection();
        $this->myFrinds = new ArrayCollection();
        $this->messagesSend = new ArrayCollection();
        $this->messagesReceved = new ArrayCollection();
        $this->messageVus = new ArrayCollection();
        $this->articles = new ArrayCollection();
        $this->articleVus = new ArrayCollection();
        $this->likeArticles = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
//        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }  public function getConfirmPassword(): string
    {
        return (string) $this->confirm_password;
    }

    public function setConfirmPassword(string $password): self
    {
        $this->confirm_password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(?string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(?string $job): self
    {
        $this->job = $job;

        return $this;
    }

    /**
     * @return Collection|UserPhoto[]
     */
    public function getUserPhotos(): Collection
    {
        return $this->userPhotos;
    }

    public function addUserPhoto(UserPhoto $userPhoto): self
    {
        if (!$this->userPhotos->contains($userPhoto)) {
            $this->userPhotos[] = $userPhoto;
            $userPhoto->setUser($this);
        }

        return $this;
    }

    public function removeUserPhoto(UserPhoto $userPhoto): self
    {
        if ($this->userPhotos->removeElement($userPhoto)) {
            // set the owning side to null (unless already changed)
            if ($userPhoto->getUser() === $this) {
                $userPhoto->setUser(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getFrinds(): Collection
    {
        return $this->Frinds;
    }

    public function addFrind(self $frind): self
    {
        if (!$this->Frinds->contains($frind)) {
            $this->Frinds[] = $frind;
        }else{
            $this->Frinds->removeElement($frind);
        }

        return $this;
    }

    public function removeFrind(self $frind): self
    {
        $this->Frinds->removeElement($frind);

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getMyFrind(): Collection
    {
        return $this->myFrinds;
    }

    public function addMyFrind(self $user): self
    {
        if (!$this->myFrinds->contains($user)) {
            $this->myFrinds[] = $user;
            $user->addFrind($this);
        }

        return $this;
    }

    public function removeMyFrind(self $user): self
    {
        if ($this->myFrinds->removeElement($user)) {
            $user->removeFrind($this);
        }

        return $this;
    }

    public function isFrind( $user): bool {
        if ($this->Frinds->contains($user)) {
            return true;
        }else{
            return false;
        }
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessagesSend(): Collection
    {
        return $this->messagesSend;
    }

    public function getMessagesSendBy($id)
    {

        $messages_t =  $this->messagesSend;
        $messages = new ArrayCollection();
        foreach ($messages_t as $value){
            if ($value->getUserReceved()->getId() == $id){
                $messages->add($value);
            }
        }
        return $messages;
    }

    public function addMessagesSend(Message $messagesSend): self
    {
        if (!$this->messagesSend->contains($messagesSend)) {
            $this->messagesSend[] = $messagesSend;
            $messagesSend->setUserSend($this);
        }

        return $this;
    }

    public function removeMessagesSend(Message $messagesSend): self
    {
        if ($this->messagesSend->removeElement($messagesSend)) {
            // set the owning side to null (unless already changed)
            if ($messagesSend->getUserSend() === $this) {
                $messagesSend->setUserSend(null);
            }

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta
            name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link
            rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
    <link rel="icon" type="image/png" href="../../dist/img/logo.png" />
    <title>
        MySite |
        {% block title %}{% endblock %}
    </title>
    {# Run `composer require symfony/webpack-encore-bundle`
                       and uncomment the following Encore helpers to start using Symfony UX #}
    {% block stylesheets %}
        {#{{ encore_entry_link_tags('app') }}#}
    {% endblock %}

    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <script src="{{ asset('dist/js/w3color.js') }}"></script>
    <!-- AdminLTE for demo purposes -->
    {% block javascripts %}
        {#{{ encore_entry_script_tags('app') }}#}
    {% endblock %}
</head>
<style>
    .style_body{
        height: 700px;
        display: block;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        background-color: black;
        /*background-color: rgba(255,255,255,0.5);*/
        background-image: linear-gradient(rgba(255,255,255,1),rgba(100,100,130,0.8)), url('../../dist/img/photo4.jpg');
    }
    .style_contenu {
        margin: 20px;
        margin-top: 35px;
        padding: 20px;
        padding-bottom: 50px;


        background-color: rgba(255,255,255,0.6);
        min-height: 600px!important;
    }
</style>

<body class="style_body layout-navbar-fixed sidebar-collapse sidebar-mini control-sidebar-slide-open sidebar-closed sidebar-collapse layout-fixed layout-navbar-fixed layout-footer-fixed">
{% include "navBar.html.twig"  %}
{% include "sideBar.html.twig"  %}
<div class="content-wrapper style_contenu" style=" ">


{% block body %}
{% endblock %}
</div>
</body>
<footer class=" main-footer" style="    bottom: 0; border-top:none ;
    position: fixed; width: 100%; background :linear-gradient(#000000b3, {{ app.user.style? app.user.style.navColor : '' }}) ">
    <strong>Copyright © 2021 <a>MySite</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b>  2
    </div>
</footer>
<aside class="theme control-sidebar control-sidebar-dark" style="top: 57px; height: 609px; display: none;">
    <!-- Control sidebar content goes here -->
    <div class="p-3 control-sidebar-content os-host os-theme-light os-host-resize-disabled os-host-scrollbar-horizontal-hidden os-host-transition os-host-overflow os-host-overflow-y" style="height: 609px;">
        <div class="os-resize-observer-host observed">
            <div class="os-resize-observer" style="left: 0px; right: auto;"></div>
        </div>
        <div class="os-size-auto-observer observed" style="height: calc(100% + 1px); float: left;"><div class="os-resize-observer"></div></div><div class="os-content-glue" style="margin: -16px;"></div>
        <div class="os-padding"><div class="os-viewport os-viewport-native-scrollbars-invisible" ><div class="os-content" style="padding: 16px; height: 100%; width: 100%;">
                    <h5>Customize Style</h5><hr class="mb-2">

                    {% set listes = ['red','purple','green','blue','olive','lightsalmon','black','Tomato'] %}
                    {% for liste in listes %}

                        <div class="mb-1" style="display: inline;background-color: {{ liste }}">
                            <a id="dark" class="xx m-2 " >{{ liste }}</a>
                        </div>

                    {% endfor %}

                    <div class="">
                        <div class="">
                            <div class="">
                            </div>
                            <div class="">
                                <div id="rgbresult" style=""><a class="xx m-2" id="rgbresulttext" style=""></a></div>
                            </div>
                            <div class="">
                            </div>
                        </div>
                        <div class="r">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-red"></span>
                                </div>
                                <input onchange="changeRGB()" oninput="changeRGB()" type="range" id="slideRed" name="slideRed" value="130" min="0" max="255">
{#                                <input type="text" class="form-control">#}
                                <div class="input-group-append">
                                    <span id="valRed2" xstyle="background-color:red;border-radius:5px;color:white;opacity:0.8">0</span>
{#                                    <span class="input-group-text">.00</span>#}
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-green"></span>
                                </div>
{#                                <input type="text" class="form-control">#}
                                <input onchange="changeRGB()" oninput="changeRGB()" type="range" id="slideGreen" name="slideGreen" value="130" min="0" max="255">
                                <div class="input-group-append">
{#                                    <span class="input-group-text">.00</span>#}
                                    <span id="valGreen2" xstyle="background-color:#00ff00;border-radius:5px;opacity:0.8">0</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-blue"></span>
                                </div>
                                    <input onchange="changeRGB()" oninput="changeRGB()" type="range" id="slideBlue" name="slideBlue" value="130" min="0" max="255">
                                <div class="input-group-append">
                                    <span id="valBlue2" xstyle="background-color:blue;border-radius:5px;color:white;opacity:0.8">0</span>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="mb-4">
                        <form class="form" method="get" action="{{ path('home') }}">
                            <input id="navcolor" type="hidden" name="navcolor" value="">
                            <input type="submit" class=" btn btn-primary btn-sm form-control" value="save">
                        </form>

                    </div>


                </div>
            </div>
        </div>
    </div>
</aside>

    {% if app.user.style %}
        {% if app.user.style.navColor %}
            <script>
                    {#$('nav').css( 'background-color', '{{ app.user.style.navColor }}' );#}
                    $('.theme').css('background', 'linear-gradient(#00000000, rgb(31 29 29 / 55%)),{{ app.user.style.navColor }}' );
                    {#$('.theme').css('background', 'linear-gradient({{ app.user.style.navColor }},rgb(7 ,7 ,240 , 0.4)),rgba(255,2,238,0.4)' );#}
                    {#$('.main-sidebar').css( 'background-color', '{{ app.user.style.navColor }}' );#}
            </script>
        {% endif %}
    {% endif %}
    <script>

        $('.xx').on( "click", function() {
        // $('nav').css( 'background-color', $(this).text() +'' );
            $('.theme').css('background','linear-gradient(#00000000, rgb(31 29 29 / 55%)),'+ $(this).text() );
        // $('.theme').css('background', 'linear-gradient('+$(this).text()+',rgb(7 ,7 ,240 , 0.4)),rgba(255,2,238,1)');
        $('#navcolor').val($(this).text() );

        });
    </script>
<script>

    changeRGB("r");
    function changeRGB(x) {
        var col, r, g, b;
        r = document.getElementById("slideRed").value;
        g = document.getElementById("slideGreen").value;
        b = document.getElementById("slideBlue").value;
        col = w3color("rgb(" + r + "," + g + "," + b + ")");
        document.getElementById('valRed2').innerHTML = r;
        document.getElementById('valGreen2').innerHTML = g;
        document.getElementById('valBlue2').innerHTML = b;
        document.getElementById('rgbresult').style.backgroundColor = col.toRgbString();
        document.getElementById('rgbresulttext').innerHTML = col.toRgbString();


        if (col.isDark(150)) {
            document.getElementById('rgbresulttext').style.color = "#ffffff";
        } else {
            document.getElementById('rgbresulttext').style.color = "#1f2d3d";
        }
    }

</script>

</html>

{#<script src="../../dist/js/demo/.js"></script></html>#}

templates/base_login.html.twig
<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta
                name="viewport" content="width=device-width, initial-scale=1">
        <!-- Font Awesome -->
        <link
                rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
{#        <!-- Theme style -->#}
        <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
        <title>
            MySite |
            {% block title %}{% endblock %}
        </title>
        {# Run `composer require symfony/webpack-encore-bundle`
                           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        <!-- jQuery -->
        <script src="../../plugins/jquery/jquery.min.js"></script>
        <!-- Bootstrap 4 -->
        <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- AdminLTE App -->
{#        <script src="../../dist/js/adminlte.min.js"></script>#}
        <!-- AdminLTE for demo purposes -->
        {% block javascripts %}

        {% endblock %}
        <style>
            .style_body{
                height: 700px;
                display: block;
                background-repeat: no-repeat;
                background-size: cover;
                background-position: center;
                background-attachment: fixed;

                background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.9)), url('../../dist/img/photo4.jpg');
            }
        </style>

    </head>


    <body class="style_body" style="height: 100%" >
        {% block body %}{% endblock %}

    </body>

</html>

templates/sideBar.html.twig
<aside class="theme main-sidebar sidebar-dark-primary elevation-4" style="background-color: rgba(0,0,0,0.5)">
    <!-- Brand Logo -->
    <a style="background-color: rgba(0,0,0,0.3)" href="" class="brand-link">
        <img src="../../dist/img/logo.png" alt=" Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span  class="brand-text font-weight-light">My Site</span>
    </a>

    <!-- Sidebar -->
    <div style="background-color: rgba(0,0,0,0.2)" class="sidebar ">
        <!-- Sidebar user (optional) -->
        <div style="background-color: rgba(0,0,0,0.3)" class="user-panel mt-2  d-flex">
            <div class="image">
                <img src="/uploads/images/users/profil{{app.user.photo ? asset(app.user.photo) : '/avatar.png' }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{{ path('user_show',{'name':app.user.name}) }}" class="d-block">{{ app.user.name }}</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
            <div class="sidebar-search-results"><div class="list-group"><a href="#" class="list-group-item">
                        <div class="search-title">
                            <b class="text-light"></b>N<b class="text-light"></b>o<b class="text-light"></b> <b class="text-light"></b>e<b class="text-light"></b>l<b class="text-light"></b>e<b class="text-light"></b>m<b class="text-light"></b>e<b class="text-light"></b>n<b class="text-light"></b>t<b class="text-light"></b> <b class="text-light"></b>f<b class="text-light"></b>o<b class="text-light"></b>u<b class="text-light"></b>n<b class="text-light"></b>d<b class="text-light"></b>!<b class="text-light"></b>
                        </div>
                        <div class="search-path">

                        </div>
                    </a></div></div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul style="background-color: rgba(0,0,0,0.3)" class=" nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->

                <li class="nav-item">
                    <a style="background-color: rgba(0,0,0,0.2)" href="{{ path('home') }}" class="nav-link {{ home is defined? 'active' : ''}} ">
                        {#                        <i class="nav-icon fas fa-log"></i>#}
                        <i class=" nav-icon fas fa-home"></i>
                        <p>
                            Home
                            {#                            <span class="right badge badge-danger">New</span>#}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
{#                    <a href="{{ path('all_message_index') }}" class="nav-link {{ creepub is defined ? 'active': '' }}">#}
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-globe"></i>
                            <p>
                                Publications
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                    </a>
                    <ul class="nav  nav-treeview">
                        <li class="nav-item">
                            <a  href="{{ path('article_new') }}" class="nav-link {{ article_new is defined ? 'active': '' }}">
                                <i class="nav-icon fas fa-file"></i>
                                <p>
                                    créer un publication
{#                                    <span class="right badge badge-danger">New</span>#}
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a  href="{{ path('article_index') }}" class="nav-link {{ article_index is defined ? 'active': '' }}">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Publication
{#                                    <span class="right badge badge-danger">New</span>#}
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a  href="{{ path('my_article_index') }}" class="nav-link {{ my_article_index is defined ? 'active': '' }}">
                                <i class="nav-icon fas fa-file-invoice"></i>
                                <p>
                                    My Publication
{#                                    <span class="right badge badge-danger">New</span>#}
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-address-book"></i>
                        <p>
                            Amis
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav  nav-treeview">
                        <li class="nav-item">
                            <a  href="{{ path('user_index') }}" class="nav-link {{ amis is defined ? 'active': '' }}">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    Trouver des amis
                                    <span class="right badge badge-danger">New</span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ path('suivie_index') }}" class="nav-link {{ suivies is defined ? 'active': '' }}">
                                <i class="text-blue nav-icon fas fa-users"></i>
                                <p>
                                    suivies
                                    <span class="right badge badge-info">{{ app.user.frinds | length }}</span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ path('abonnee_index') }}" class="nav-link {{ abonnee is defined ? 'active': '' }}">
                                <i class="text-red nav-icon fas fa-users"></i>
                                <p>
                                    Abonnees
                                    <span class="right badge badge-info">{{ app.user.MyFrind | length }}</span>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{{ path('all_message_index') }}" class="nav-link {{ msg is defined ? 'active': '' }}">
                        <i class="nav-icon fas fa-envelope"></i>
                        <p>
                            Messages
                            <span class="right badge badge-danger ">{{ app.user.allNewMessage(app.user.id)['messages'] | length }}</span>
{#                            <span class="right badge badge-danger">New</span>#}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ path('app_logout') }}" class="nav-link">
{#                        <i class="nav-icon fas fa-log"></i>#}
                        <i class=" nav-icon fas fa-sign-out-alt"></i>
                        <p>
                           logout
{#                            <span class="right badge badge-danger">New</span>#}
                        </p>
                    </a>
                </li>
                {#                <li class="nav-item">#}
{#                    <a href="{{ path('user_index') }}" class="nav-link">#}
{#                        <i class="nav-icon fas fa-users"></i>#}
{#                        <p>#}
{#                            Trouver des amis#}
{#                            <span class="right badge badge-danger">New</span>#}
{#                        </p>#}
{#                    </a>#}
{#                </li>#}


            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>